USE [PeiLiu.BudgetTracker]
GO
SET IDENTITY_INSERT [dbo].[Expenditures] ON 
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (12, CAST(750.00 AS Decimal(18, 2)), N'Household', 12)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (13, CAST(753.00 AS Decimal(18, 2)), N'Dining', 12)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (14, CAST(650.00 AS Decimal(18, 2)), N'Household', 13)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (15, CAST(653.00 AS Decimal(18, 2)), N'Dining', 13)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (16, CAST(770.00 AS Decimal(18, 2)), N'Household', 14)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (17, CAST(757.00 AS Decimal(18, 2)), N'Dining', 14)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (18, CAST(958.00 AS Decimal(18, 2)), N'Household', 15)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (19, CAST(193.00 AS Decimal(18, 2)), N'Dining', 15)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (20, CAST(102.00 AS Decimal(18, 2)), N'Household', 16)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (21, CAST(753.00 AS Decimal(18, 2)), N'Dining', 16)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (22, CAST(657.00 AS Decimal(18, 2)), N'Household', 17)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (23, CAST(603.00 AS Decimal(18, 2)), N'Dining', 17)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (24, CAST(370.00 AS Decimal(18, 2)), N'Household', 18)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (25, CAST(737.00 AS Decimal(18, 2)), N'Dining', 18)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (26, CAST(750.00 AS Decimal(18, 2)), N'Household', 19)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (27, CAST(157.00 AS Decimal(18, 2)), N'Dining', 19)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (28, CAST(720.00 AS Decimal(18, 2)), N'Household', 20)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (29, CAST(957.00 AS Decimal(18, 2)), N'Dining', 20)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (30, CAST(798.00 AS Decimal(18, 2)), N'Household', 21)
INSERT [dbo].[Expenditures] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (31, CAST(153.00 AS Decimal(18, 2)), N'Dining', 21)