USE [PeiLiu.BudgetTracker]
GO
SET IDENTITY_INSERT [dbo].[Incomes] ON 
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (12, CAST(7500.00 AS Decimal(18, 2)), N'Payroll', 12)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (13, CAST(7534.00 AS Decimal(18, 2)), N'Earnings', 12)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (14, CAST(6500.00 AS Decimal(18, 2)), N'Payroll', 13)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (15, CAST(6534.00 AS Decimal(18, 2)), N'Earnings', 13)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (16, CAST(7700.00 AS Decimal(18, 2)), N'Payroll', 14)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (17, CAST(7574.00 AS Decimal(18, 2)), N'Earnings', 14)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (18, CAST(9580.00 AS Decimal(18, 2)), N'Payroll', 15)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (19, CAST(1934.00 AS Decimal(18, 2)), N'Earnings', 15)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (20, CAST(1020.00 AS Decimal(18, 2)), N'Payroll', 16)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (21, CAST(7534.00 AS Decimal(18, 2)), N'Earnings', 16)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (22, CAST(6570.00 AS Decimal(18, 2)), N'Payroll', 17)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (23, CAST(6034.00 AS Decimal(18, 2)), N'Earnings', 17)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (24, CAST(3700.00 AS Decimal(18, 2)), N'Payroll', 18)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (25, CAST(7374.00 AS Decimal(18, 2)), N'Earnings', 18)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (26, CAST(7500.00 AS Decimal(18, 2)), N'Payroll', 19)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (27, CAST(1574.00 AS Decimal(18, 2)), N'Earnings', 19)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (28, CAST(7200.00 AS Decimal(18, 2)), N'Payroll', 20)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (29, CAST(9574.00 AS Decimal(18, 2)), N'Earnings', 20)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (30, CAST(7980.00 AS Decimal(18, 2)), N'Payroll', 21)
INSERT [dbo].[Incomes] ([Id], [Amount], [Description], [UsersId]) 
	VALUES (31, CAST(1536.00 AS Decimal(18, 2)), N'Earnings', 21)